name: Run Tests

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
       
    steps:
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 2.0.x

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0


    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
