name: Run Tests

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '2.0.x' ]       
    steps:
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 2.0.x

    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore dependencies
      run: dotnet restore

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      
    - name: Build
      run: msbuild PortTunnel_forWindowsXP_1.sln
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
